### PR TITLE
Get multiple header values with same key

### PR DESCRIPTION
**Pull request by nsagnett**
Implementation for get multiple header values with same key : https://github.com/valyala/fasthttp/issues/179

(Sorry for all other changes -> IDEA indentation)

### CODE REVIEW

**Comment by bogem** [comment]
I think, you should `gofmt` your code

**Comment by ilaipx** [comment]
@bogem How's this going? Is this gonna be released, or was released already?

**Comment by bogem** [comment]
@ilaipx I don't know, I'm not a maintainer of this library

**Comment by erikdubbelboer** [comment]
https://github.com/erikdubbelboer/fasthttp is the maintained version of fasthttp, if you make a pull request there I'll have a look at it.

**Comment by erikdubbelboer** [comment]
If you are still interested in this change please rebase it on master and reopen this pull request. Thanks.

**Pull request closed without merging**
