### PR TITLE
fix the gracefully shutdown

### PR DESCRIPTION
**Pull request by wilhelmliao**
The Ctrl+C will interrupt the server process immediately without wait active connections finish.
I change the Shutdown() make it perfectly.

The following sample can help to reproduce the scenario.
```go
package main

import (
	"log"
	"net"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/valyala/fasthttp"
)

var address = ":38080"

func connStateCallback(conn net.Conn, state fasthttp.ConnState) {
	log.Printf("conn: %+v\n", conn)
	log.Printf("state: %+v\n", state)
}

func main() {
	handler := processRequest

	server := &fasthttp.Server{
		Handler:                       handler,
		Name:                          "Demo Service",
		DisableKeepalive:              true,
		DisableHeaderNamesNormalizing: true,
		ConnState:                     connStateCallback,
	}

	signalChan := make(chan os.Signal, 1)
	signal.Notify(signalChan, os.Interrupt, syscall.SIGTERM)
	//register for interupt (Ctrl+C) and SIGTERM (docker)
	go func() {
		<-signalChan
		log.Printf("server.Shutdown()")
		server.Shutdown()
	}()

	log.Printf("%s listening on address %s\n", server.Name, address)
	if err := server.ListenAndServe(address); err != nil {
		log.Fatalf("Error in ListenAndServe: %s\n", err)
	}
}

func processRequest(ctx *fasthttp.RequestCtx) {
	ctx.Conn()
	time.Sleep(time.Second * 10)
	ctx.Success("text/plain", []byte("123"))
	log.Printf("connection '%+v' finshed\n", ctx.Conn())
	return
}
```

### CODE REVIEW

**Comment by erikdubbelboer** [comment]
The way it currently works is the exact same way as [`net/http.Server.Shutdown()`](https://golang.org/pkg/net/http/#Server.Shutdown) works. From that documentation:
```
When Shutdown is called, Serve, ListenAndServe, and ListenAndServeTLS immediately
return ErrServerClosed. Make sure the program doesn't exit and waits instead for
Shutdown to return. 
```
fasthttp [has the exact same line in the documentation for `Shutdown()`](https://godoc.org/github.com/valyala/fasthttp#Server.Shutdown)!

**Comment by wilhelmliao** [comment]
Is there way to shutdown a server process without interrupting critical running tasks?

For example, I want load data from database A and write the data to database B and database C in a single request handler. I want the server.Shutdown() will wait for the operation finished.

**Comment by erikdubbelboer** [comment]
Yes you just have to switch it around. You do your `ListenAndServe` in a goroutine and `Shutdown` in your main goroutine:
```go
package main

import (
	"log"
	"net"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/valyala/fasthttp"
)

var address = ":38080"

func connStateCallback(conn net.Conn, state fasthttp.ConnState) {
	log.Printf("conn: %+v\n", conn)
	log.Printf("state: %+v\n", state)
}

func main() {
	handler := processRequest

	server := &fasthttp.Server{
		Handler:                       handler,
		Name:                          "Demo Service",
		DisableKeepalive:              true,
		DisableHeaderNamesNormalizing: true,
		ConnState:                     connStateCallback,
	}

	go func() {
		log.Printf("%s listening on address %s\n", server.Name, address)
		if err := server.ListenAndServe(address); err != nil {
			log.Fatalf("Error in ListenAndServe: %s\n", err)
		}
	}()

	signalChan := make(chan os.Signal, 1)
	signal.Notify(signalChan, os.Interrupt, syscall.SIGTERM)
	//register for interupt (Ctrl+C) and SIGTERM (docker)
	<-signalChan
	log.Printf("server.Shutdown()")
	server.Shutdown()
}

func processRequest(ctx *fasthttp.RequestCtx) {
	ctx.Conn()
	time.Sleep(time.Second * 10)
	ctx.Success("text/plain", []byte("123"))
	log.Printf("connection '%+v' finshed\n", ctx.Conn())
	return
}
```

**Comment by wilhelmliao** [comment]
Thank you, @erikdubbelboer ! It work well :)

**Pull request closed without merging**
