### PR TITLE
fix x86 atomic.AddUint64

### PR DESCRIPTION
**Pull request by vinhjaxt**
This commit fix atomic.AddUint64 in client.go on x86 os

### CODE REVIEW

**Comment by erikdubbelboer** [comment]
I'm not sure what this is supposed to do, it just moves the exact same member to another line in the struct?

**Comment by vinhjaxt** [comment]
Move pendingRequests to the top of the struct will fix problem (panic on line 996 in client.go) on x86 machine,
reference by this: https://golang.org/pkg/sync/atomic/#pkg-note-BUG
sorry for my poor english

**Comment by vinhjaxt** [comment]
`set GOOS=linux`
`set GOARCH=386`
`go build`
and run it on
`Linux xxxx 2.6.32-696.10.2.el6.i686 #1 SMP Tue Sep 12 13:54:13 UTC 2017 i686 i686 i386 GNU/Linux`
will cause:
`
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8049e5c]

goroutine 17 [running]:
runtime/internal/atomic.Xadd64(0x940a3b4, 0x1, 0x0, 0x942ff34, 0x9401ce0)
        xxx/go/src/runtime/internal/atomic/asm_386.s:102 +0xc
github.com/valyala/fasthttp.(*HostClient).Do(0x940a300, 0x9480420, 0x9484680, 0x9449ba0, 0x9458c18)
        xxx/go/yyy/src/github.com/valyala/fasthttp/client.go:995 +0x4f
github.com/valyala/fasthttp.(*Client).Do(0x945a370, 0x9480420, 0x9484680, 0x0, 0x1)
        xxx/go/yyy/src/github.com/valyala/fasthttp/client.go:416 +0x15f
github.com/valyala/fasthttp.clientDoDeadline.func1(0x944a940, 0x84480f0, 0x945a370, 0x9480420, 0x9484680)
        xxx/go/yyy/src/github.com/valyala/fasthttp/client.go:947 +0x35
created by github.com/valyala/fasthttp.clientDoDeadline
        xxx/go/yyy/src/github.com/valyala/fasthttp/client.go:946 +0x1b5
`

**Comment by erikdubbelboer** [comment]
That's interesting, I didn't know that was an issue. But I'm in favor of just changing it to an `uint32` instead. Nobody will ever have more than `2^32` pending requests. @kirillDanshin what do you think?

**Comment by erikdubbelboer** [comment]
Fixed in https://github.com/valyala/fasthttp/commit/8f4c5d5d1dbb772a29f059645f0f03a4556c1dad

**Pull request closed without merging**
