### PR TITLE
Added Gearbox

### PR DESCRIPTION
**Pull request by muhammednagy**
Gearbox is a web framework written in Go with a focus on high performance and memory optimization.

### CODE REVIEW

**Comment by erikdubbelboer** [comment]
To be honest I'm wondering if we should just add everything that uses fasthttp to the readme. This framework has only 22 commits, and doesn't seem to have any users except for the creators.

**Comment by muhammednagy** [comment]
I understand.
You do have a valid point. however, we are working hard on improving it every day and we promise something good ( and have good progress so far ).
If you would like you could keep this issue open till we release our first stable release ( in a month or less )

**Comment by proyb6** [comment]
@muhammednagy Good luck! From SG.

**Comment by muhammednagy** [comment]
Hey @erikdubbelboer 
We have released a stable version now.
I know 30 commits is not much but please give it a chance. we are offering some pretty cool features like LRU caching for routes and the TST routing which already makes it faster than almost all current Go frameworks.

**Comment by muhammednagy** [comment]
Hey @erikdubbelboer 
So we have checked and apparently the map is faster.
So we switched to map now and we are waiting for a newer proper benchmark.
However, even when we were using TST we were the fifth fastest framework.
I think you should give it a chance :)

**Comment by erikdubbelboer** [comment]
Ok here you go!

**Comment by muhammednagy** [comment]
Thank you! @erikdubbelboer

**Pull request merged**
