### PR TITLE
replace s2b function with the recommended one

### PR DESCRIPTION
**Pull request by efectn**
ref https://github.com/gofiber/fiber/issues/2180

### CODE REVIEW

**Comment by erikdubbelboer** [comment]
I'm going to hold of on this one until we can use [`unsafe.String`](https://pkg.go.dev/unsafe@master#String) and [`unsafe.StringData`](https://pkg.go.dev/unsafe@master#StringData) which are the real future proof ways to do this.

**Comment by efectn** [comment]
> I'm going to hold of on this one until we can use [`unsafe.String`](https://pkg.go.dev/unsafe@master#String) and [`unsafe.StringData`](https://pkg.go.dev/unsafe@master#StringData) which are the real future proof ways to do this.

Agree but it will be available on Go 1.20. I think we can't use it on Fasthttp.

**Comment by erikdubbelboer** [comment]
We can. We just put the current `s2b` etc functions in a file that only gets used with go 1.19 or lower and use `unsafe.String` etc in a file that gets used with go 1.20 or higher.

**Comment by stokito** [comment]
Could you please elaborate, so starting from Go1.20 the s2b() will not work?
I'm asking because for my project I also needed the func and I copied it to a module
https://github.com/stokito/go-strbytes
So I have to update it too.

It would be great if the FastHttp makes the func public or extracted to a some utils module so that users can easily update.

**Comment by erikdubbelboer** [comment]
`s2b` will still work fine in Go 1.20.

But what we can do is have 1 file with something like:
```go
//go:build go1.20

func s2b(s string) []byte {
	return unsafe.Slice(unsafe.StringData(s), len(s))
}
```
and another with the old `s2b` implementation and this build tag:
```go
//go:build !go1.20
```

**Comment by erikdubbelboer** [comment]
Fixed in https://github.com/valyala/fasthttp/pull/1481

**Pull request closed without merging**
