### PR TITLE
feat(fasthttpproxy): add dual-stack connection support to enable IPv6 proxies for HTTP and SOCKS5 dialers

### PR DESCRIPTION
**Pull request by lavish440**
- Added `FasthttpHTTPDialerDualStack` to support dual-stack (IPv4 and IPv6) connections for HTTP proxies, enabling IPv6 proxy usage.
- Added `FasthttpSocksDialerDualStack` to support dual-stack (IPv4 and IPv6) connections for SOCKS5 proxies, enabling IPv6 proxy usage.
- Improved dialer configuration to ensure compatibility with both IPv4 and IPv6 proxies.

### CODE REVIEW

**Review by alexandear — CHANGES_REQUESTED** [review]
Please fix lint issues.

https://github.com/valyala/fasthttp/actions/runs/11304905672/job/31753981246

**Comment by lavish440** [comment]
@alexandear Done

**Comment by alexandear** [comment]
Looks like it's not fully fixed.

**Comment by lavish440** [comment]
> Looks like it's not fully fixed.

Done. 
Seems like golangci-lint does not like goimports-reviser

**Comment by erikdubbelboer** [comment]
Thanks!

**Pull request merged**
