### PR TITLE
better optimizations

### PR DESCRIPTION
**Pull request by EricLagergren**
* bytesconv.go:
    - used better algorithm for convering int -> []byte in AppendUint
        (see _testdata for benchmark and asm breakdown.)
    - uppercasByte and lowerCase byte return instead of chasing pointers
    - EqualBytesStr uses unsafe package to cast a string into []byte
        without any allocs
    - normalizeHeaderKey now doesn't need any flags.
    - switched a lot of normal for-loops into for-range loops because
        the compiler will elide bounds checking for range loops.

### CODE REVIEW

**Comment by valyala** [comment]
@EricLagergren , could you rebase the pull request on the top of fasthttp master? It looks like certain optimizations from the pull request were already done on this week.

**Comment by valyala** [comment]
Eric, there are few concerns regarding the pull request:

* It doesn't pass tests at the moment. Fix, please, all `go test` tests. Start with `go test -run=Header`.
* Make sure that each optimization really leads to performance improvement via running the corresponding benchmark with `go test -bench=.` .

**Comment by EricLagergren** [comment]
oh. when editing normalizeHederKeys I forgot that go's switch statements have an implicit break.

**Comment by valyala** [comment]
Eric, it looks like the optimization for normalizeHeaderKey doesn't work:

Master branch:
```
$ go test -bench=Normalize -benchmem
PASS
BenchmarkNormalizeHeaderKeyCommonCase-4	30000000	        45.6 ns/op	       0 B/op	       0 allocs/op
BenchmarkNormalizeHeaderKeyLowercase-4 	30000000	        43.7 ns/op	       0 B/op	       0 allocs/op
BenchmarkNormalizeHeaderKeyUppercase-4 	30000000	        45.8 ns/op	       0 B/op	       0 allocs/op
```

Your branch:
```
$ go test -bench=Normalize -benchmem
PASS
BenchmarkNormalizeHeaderKeyCommonCase-4	30000000	        58.1 ns/op	       0 B/op	       0 allocs/op
BenchmarkNormalizeHeaderKeyLowercase-4 	20000000	        60.1 ns/op	       0 B/op	       0 allocs/op
BenchmarkNormalizeHeaderKeyUppercase-4 	30000000	        51.1 ns/op	       0 B/op	       0 allocs/op
```

AppendUint optimization works:

Master branch:
```
$ go test -bench=AppendUint -benchmem
PASS
BenchmarkAppendUint-4	100000000	        18.2 ns/op	       0 B/op	       0 allocs/op
```

Your branch:
```
$ go test -bench=AppendUint -benchmem
PASS
BenchmarkAppendUint-4	100000000	        13.0 ns/op	       0 B/op	       0 allocs/op
```

So I manually integrated only AppendUint optimization from the pull request.

**Comment by EricLagergren** [comment]
Oddly enough I got opposite results on my machine:

Master branch:
```
eric@archbox /tmp/fasthttp $ go test -bench=Normalize -benchmem
PASS
BenchmarkNormalizeHeaderKeyCommonCase-4	20000000	       118 ns/op	       0 B/op	       0 allocs/op
BenchmarkNormalizeHeaderKeyLowercase-4 	20000000	       123 ns/op	       0 B/op	       0 allocs/op
BenchmarkNormalizeHeaderKeyUppercase-4 	20000000	       137 ns/op	       0 B/op	       0 allocs/op
ok  	_/tmp/fasthttp	10.411s
```

My branch:
```
eric@archbox ~/gopath/src/github.com/EricLagergren/fasthttp $ go test -bench=Normalize -benchmem
PASS
BenchmarkNormalizeHeaderKeyCommonCase-4	20000000	       117 ns/op	       0 B/op	       0 allocs/op
BenchmarkNormalizeHeaderKeyLowercase-4 	20000000	       108 ns/op	       0 B/op	       0 allocs/op
BenchmarkNormalizeHeaderKeyUppercase-4 	20000000	       107 ns/op	       0 B/op	       0 allocs/op
ok  	github.com/EricLagergren/fasthttp	9.077s
```

**Comment by valyala** [comment]
Note that the performance for common case `BenchmarkNormalizeHeaderKeyCommonCase` didn't change significantly. Two other benchmarks are just for completeness - they are far from real use cases.

**Comment by EricLagergren** [comment]
If you're really interested in microbenchmarks you might try a simple `for i := range` loop. It's odd that a traditional loop would out-perform a range loop, since ranges elide bounds checking... but I never checked to see what assembly the compiler generated, and Go's compiler can be finicky.

**Comment by valyala** [comment]
Closing this pull request, since the only remaining optimization for `normalizeHeaderKey` doesn't give significant performance improvement. @EricLagergren , thanks for other performance improvements from your merge request, which were integrated into fasthttp.

**Pull request closed without merging**
