### PR TITLE
Wait for the response of pipelineWork in background and return it to pool

### PR DESCRIPTION
**Pull request by panjf2000**
Updates #1433

### CODE REVIEW

**Comment by panjf2000** [comment]
@erikdubbelboer PTAL

**Review by erikdubbelboer — CHANGES_REQUESTED** [review]
I don't think this is worth the effort. The goroutine probably has a bigger overhead than just letting the allocation go to waste and having to allocate a new w next time don't you think?

**Comment by panjf2000** [comment]
> I don't think this is worth the effort. The goroutine probably has a bigger overhead than just letting the allocation go to waste and having to allocate a new w next time don't you think?

Well, the memory waste caused by the case of timeout is indeed rare, I guess we can live with that, also thanks for your reply.

**Comment by Tristin-C** [comment]
Big man, is that going to lead to a leak? Causing the number of coroutines to soar? Because I seem to have that problem

**Pull request closed without merging**
