### PR TITLE
get rid of some panics

### PR DESCRIPTION
**Pull request by mpldr**
Addresses #1522 and #1504. The latter is not fixed, but only referenced as the underlying double-close is not resolved.

Fixes: #1522

### CODE REVIEW

**Review by erikdubbelboer — CHANGES_REQUESTED** [review]
Can you fix the linting errors.

**Comment by mpldr** [comment]
On Sun Mar 26, 2023 at 10:28 PM CEST, Erik Dubbelboer wrote:
> Can you fix the linting errors.

Will do, still not completely through, I also want to add commentary
explaining why the remaining panics should stay.
-- 
Moritz Poldrack
https://moritz.sh

**Comment by mpldr** [comment]
/shrug Can't do anything about the tests taking too long

**Comment by erikdubbelboer** [comment]
Thanks!

**Pull request merged**
