### PR TITLE
Resolve code issues from goreportcard.com

### PR DESCRIPTION
**Pull request by panjf2000**
Resolve the remaining code issues on https://goreportcard.com/report/github.com/valyala/fasthttp.

### CODE REVIEW

**Comment by panjf2000** [comment]
@erikdubbelboer

**Comment by panjf2000** [comment]
image
That is odd, I got a pass on my MacBook Pro and it is only failed one OSX job, else are all successful, is it occasional or what?

**Comment by panjf2000** [comment]
@erikdubbelboer 
Could you retry that failed job to verify whether it is just an occasional failure?

**Comment by panjf2000** [comment]
Well, all tests pass on my CI: https://travis-ci.com/panjf2000/fasthttp

**Comment by erikdubbelboer** [comment]
Thanks!

**Pull request merged**
