### PR TITLE
Fix mCleaner not cleaning Ms fix.

### PR DESCRIPTION
**Pull request by moredure**
Fixing fix https://github.com/valyala/fasthttp/pull/975

### CODE REVIEW

**Comment by kiyonlin** [comment]
Well done! I can't believe I missed other 2 `c.m` 😢

**Comment by moredure** [comment]
Yeap, I also missed them at first) But understanding comes later))

**Comment by moredure** [comment]
I hope that we don't need fix to fix the fix)

**Comment by erikdubbelboer** [comment]
Good catch, not sure how I missed those either, I remember Ctrl+f'ing `c.m`.

**Pull request merged**
