### PR TITLE
optimize: allow http head when use getonly

### PR DESCRIPTION
**Pull request by li-jin-gou**
pr for https://github.com/valyala/fasthttp/issues/1455

### CODE REVIEW

**Review by erikdubbelboer — CHANGES_REQUESTED** [review]
I guess it makes sense. But please also change the documentation here to reflect this: https://github.com/valyala/fasthttp/blob/2a572e08ef547b02bec1328c150ed31deec31d17/server.go#L292-L299

**Comment by li-jin-gou** [comment]
> I guess it makes sense. But please also change the documentation here to reflect this:
> 
> https://github.com/valyala/fasthttp/blob/2a572e08ef547b02bec1328c150ed31deec31d17/server.go#L292-L299

thanks and done

**Comment by erikdubbelboer** [comment]
Thanks!

**Comment by TheKigen** [comment]
Thank you.

**Pull request merged**
