### PR TITLE
Skip fs cache based on config

### LINKED ISSUE #1472: Disable Caching for FS Handler
Fasthttp FS isn't supporting disabling caching currently. Are there any way to disable it or should it be forcibly opened?

Ref: https://github.com/gofiber/fiber/issues/2201

### PR DESCRIPTION
**Pull request by peczenyj**
this should fix #1472

related to https://github.com/gofiber/fiber/issues/2201

### CODE REVIEW

**Comment by erikdubbelboer** [comment]
Can you rebase this to fix the merge conflict with your previous change? Thanks!

**Comment by peczenyj** [comment]
> Can you rebase this to fix the merge conflict with your previous change? Thanks!

I will

**Comment by peczenyj** [comment]
Done

**Comment by erikdubbelboer** [comment]
Thanks!

**Pull request merged**
