### PR TITLE
Support huge read-only []byte response bodies

### PR DESCRIPTION
**Pull request by cipriancraciun**
See issue #469.

### CODE REVIEW

**Comment by erikdubbelboer** [comment]
@cipriancraciun would it be possible for you to add some tests to make sure everything keeps working correctly in the future?

**Comment by cipriancraciun** [comment]
> @cipriancraciun would it be possible for you to add some tests to make sure everything keeps working correctly in the future?

Sorry for deferring this, but I was a little busy.  I'll try to add them during these days around new year's eve.

**Comment by cipriancraciun** [comment]
So I've rebased my two commits based on the latest code, and added a few tests at the end of `http_tests.go`.  Basically I check that the `SetBodyRaw` actually works as expected, if `CopyTo` and `ResetBody` work properly.

If I can make any other changes please let me know.

**Comment by erikdubbelboer** [comment]
Thanks.

**Pull request merged**
