### PR TITLE
Use table in appendQuotedPath and AppendQuotedArg

### PR DESCRIPTION
**Pull request by ZYunH**
The character comparison is expensive, use table is better. 

A simple benchmark for this change:
> func BenchmarkAppendQuotedArg(b *testing.B) {
	dst := make([]byte, 0, 100)
	src := []byte("foo=@bar&aaa=bbb")
	for i := 0; i < b.N; i++ {
		AppendQuotedArg(dst, src)
	}
}

BenchmarkAppendQuotedArg-12             50000000                24.2 ns/op             0 B/op          0 allocs/op
BenchmarkAppendQuotedArgNew-12            100000000               20.1 ns/op             0 B/op          0 allocs/op

The latter is the new one. And it can be inferred that the longer the input string is, the new one will be much more faster.

### CODE REVIEW

**Comment by ZYunH** [comment]
@erikdubbelboer Hi i can't get any useful informations in the failed test, it may some problems in test suites?

**Comment by erikdubbelboer** [comment]
@ZYunH the test failure is unrelated to your pull request.

**Comment by erikdubbelboer** [comment]
The latest commit in master should fix the test issue. So please rebase on master.

**Comment by ZYunH** [comment]
It looks like we don't implement correctly before? the quotedArgTable should be ALPHA / DIGIT / "-" / "." / "_" / "~". A simple test in Go official implementation

> 	u := url.Values{}
	u.Add("test","x.x*")
	print(u.Encode())

We got "test=x.x%2A", but the implementation in fasthttp, it will become "test=x.x*". We should also modify the test code since it is incorrect.

**Comment by ZYunH** [comment]
Mark our previous tests for quotedArg

key -> "f.o,1:2/4"
value -> "~`!@#$%^&*()_-=+\\|/[]{};:'\"<>,./?"

Go implementation
> "f.o%2C1%3A2%2F4=~%60%21%40%23%24%25%5E%26%2A%28%29_-%3D%2B%5C%7C%2F%5B%5D%7B%7D%3B%3A%27%22%3C%3E%2C.%2F%3F"
Fasthttp
> "f.o%2C1%3A2%2F4=%7E%60%21%40%23%24%25%5E%26*%28%29_-%3D%2B%5C%7C%2F%5B%5D%7B%7D%3B%3A%27%22%3C%3E%2C.%2F%3F"

I think we can fix it in this pull request

**Comment by ZYunH** [comment]
pls see the new pull request in https://github.com/valyala/fasthttp/pull/654

**Pull request closed without merging**
