### PR TITLE
Option for immediate header flush

### PR DESCRIPTION
**Pull request by Bobochka**
In case of body stream if first body bytes generation takes long this adds an option of "faster response".

Will add tests if general idea is ok.

### CODE REVIEW

**Comment by erikdubbelboer** [comment]
I'm wondering if this should be two functions of if it should just be an exported field named `Response.FlushHeaders bool`. What do you think @kirillDanshin ?

**Comment by Bobochka** [comment]
@erikdubbelboer @kirillDanshin Exported field and added tests

**Comment by Bobochka** [comment]
@kirillDanshin any action from my side? We're already running a fork in prod that always flushes before body.

**Comment by erikdubbelboer** [comment]
Thanks. We don't need any more testing seeing as this doesn't change anything if you don't set the value to true. And even then, just calling `w.Flush()` is not something complicated.

**Pull request merged**
