### PR TITLE
Improve round2 performance

### PR DESCRIPTION
**Pull request by kiyonlin**
I think `uint32` is enough(4GB) for current situation.

And here is the benchmark result:

Test case
```go
func BenchmarkRound2(b *testing.B) {
	b.RunParallel(func(pb *testing.PB) {
		b.ReportAllocs()
		b.ResetTimer()
		for pb.Next() {
			round2(0x10001)
		}
	})
}
```

OLD:
```hs
BenchmarkRound2-16      1000000000               0.875 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.880 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.874 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.876 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.874 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.877 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.873 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.878 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.888 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.904 ns/op           0 B/op          0 allocs/op
```

NEW:
```hs
BenchmarkRound2-16      1000000000               0.156 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.157 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.155 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.156 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.149 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.156 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.156 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.154 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.156 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.152 ns/op           0 B/op          0 allocs/op
```

benchstat:
```hs
name       old time/op    new time/op    delta
Round2-16    0.88ns ± 1%    0.16ns ± 2%  -82.29%  (p=0.000 n=9+9)

name       old alloc/op   new alloc/op   delta
Round2-16     0.00B          0.00B          ~     (all equal)

name       old allocs/op  new allocs/op  delta
Round2-16      0.00           0.00          ~     (all equal)
```

### CODE REVIEW

**Comment by ReneWerner87** [comment]
```go
NEW
Benchmark_Round/round-12       1000000000     0.380 ns/op   0 B/op   0 allocs/op
Benchmark_Round/round-12       1000000000     0.439 ns/op   0 B/op   0 allocs/op
Benchmark_Round/round-12       1000000000     0.333 ns/op   0 B/op   0 allocs/op
Benchmark_Round/round-12       1000000000     0.310 ns/op   0 B/op   0 allocs/op

OLD
Benchmark_Round/round-12       126755714     9.24 ns/op   0 B/op   0 allocs/op
Benchmark_Round/round-12       124897803     9.32 ns/op   0 B/op   0 allocs/op
Benchmark_Round/round-12       117840432     9.64 ns/op   0 B/op   0 allocs/op
Benchmark_Round/round-12       133441935     9.66 ns/op   0 B/op   0 allocs/op
```

on my machine the difference is enormous, very good improvement

**Comment by kiyonlin** [comment]
> ```go
> 
> NEW
> 
> Benchmark_Round/round-12       1000000000     0.380 ns/op   0 B/op   0 allocs/op
> 
> Benchmark_Round/round-12       1000000000     0.439 ns/op   0 B/op   0 allocs/op
> 
> Benchmark_Round/round-12       1000000000     0.333 ns/op   0 B/op   0 allocs/op
> 
> Benchmark_Round/round-12       1000000000     0.310 ns/op   0 B/op   0 allocs/op
> 
> 
> 
> OLD
> 
> Benchmark_Round/round-12       126755714     9.24 ns/op   0 B/op   0 allocs/op
> 
> Benchmark_Round/round-12       124897803     9.32 ns/op   0 B/op   0 allocs/op
> 
> Benchmark_Round/round-12       117840432     9.64 ns/op   0 B/op   0 allocs/op
> 
> Benchmark_Round/round-12       133441935     9.66 ns/op   0 B/op   0 allocs/op
> 
> ```
> 
> 
> 
> on my machine the difference is enormous, very good improvement 

Do you use `RunParallel` in your benchmark? Non-Parallel indeed gets better result.

**Comment by ReneWerner87** [comment]
```go
NEW
Benchmark_Round-12	1000000000	 0.290 ns/op  0 B/op	   0 allocs/op
Benchmark_Round-12	1000000000	 0.292 ns/op  0 B/op	   0 allocs/op
Benchmark_Round-12	1000000000	 0.313 ns/op  0 B/op	   0 allocs/op
Benchmark_Round-12	1000000000	 0.276 ns/op  0 B/op	   0 allocs/op

OLD
Benchmark_Round-12	590925472	 2.46 ns/op	   0 B/op	   0 allocs/op
Benchmark_Round-12	512504625	 2.34 ns/op	   0 B/op	   0 allocs/op
Benchmark_Round-12	513369567	 2.42 ns/op	   0 B/op	   0 allocs/op
Benchmark_Round-12	494117672	 2.46 ns/op	   0 B/op	   0 allocs/op
```
@kiyonlin thx for the hint, this is the result with RunParallel

**Comment by erikdubbelboer** [comment]
Thanks!

**Comment by kiyonlin** [comment]
Correct benchmark result, see golang/go#42865

```go
var result, input = 0, 2059

func BenchmarkRound2(b *testing.B) {
	var r int
	for i := 0; i < b.N; i++ {
		r = round2(input)
	}
	result = r
}
```

```hs
OLD
BenchmarkRound2-16      236888917                5.22 ns/op
BenchmarkRound2-16      240635983                5.11 ns/op
BenchmarkRound2-16      232815938                5.08 ns/op
BenchmarkRound2-16      238104736                5.07 ns/op
BenchmarkRound2-16      234706026                5.05 ns/op
BenchmarkRound2-16      237575134                5.11 ns/op
BenchmarkRound2-16      236359236                5.08 ns/op
BenchmarkRound2-16      235753626                5.11 ns/op
BenchmarkRound2-16      238996531                5.12 ns/op
BenchmarkRound2-16      236190168                5.03 ns/op

NEW
BenchmarkRound2-16      851576810                1.40 ns/op
BenchmarkRound2-16      834691317                1.37 ns/op
BenchmarkRound2-16      883740036                1.38 ns/op
BenchmarkRound2-16      863867149                1.38 ns/op
BenchmarkRound2-16      870876801                1.37 ns/op
BenchmarkRound2-16      846145068                1.42 ns/op
BenchmarkRound2-16      870322744                1.37 ns/op
BenchmarkRound2-16      874905960                1.36 ns/op
BenchmarkRound2-16      873266862                1.38 ns/op
BenchmarkRound2-16      873845012                1.37 ns/op
```

benchstat
```hs
name       old time/op  new time/op  delta
Round2-16  5.08ns ± 1%  1.37ns ± 1%  -73.01%  (p=0.000 n=9+8)
```

Sorry about the misleading @ReneWerner87

**Pull request merged**
