### PR TITLE
change req.timeout to public and add min deadline in pipeline

### PR DESCRIPTION
**Pull request by fare83**
change req.timeout to public for Do method support timeout; 
add timeout in clientGetURLDeadline;
add min deadline in pipeline

### CODE REVIEW

**Comment by erikdubbelboer** [comment]
Can you explain why you need `Request.Timeout` to be public?

**Comment by fare83** [comment]
when i use hostclient.Do ，i can't set timeout

**Comment by erikdubbelboer** [comment]
But that internal timeout is only used as a timeout to acquire a connection if you have `MaxConns` set. What I would actually much rather do is make that timeout equal to `WriteTimeout` and completely get rid of `req.timeout`.

**Comment by fare83** [comment]
I want to set timeout for current request, but writetimeout is for all host and request.

**Comment by erikdubbelboer** [comment]
What do you think of this instead: https://github.com/valyala/fasthttp/pull/1346
`HostClient` already has `DoTimeout` and `DoDeadline`. What this pull request does it just make them use `req.timeout` instead of the separate goroutine that I have always hated.

**Comment by fare83** [comment]
#1346 LGTM

**Pull request closed without merging**
