### PR TITLE
WIP: Add defense against slowloris attack

### PR DESCRIPTION
**Pull request by mxmauro**
Hi @valyala and @erikdubbelboer, I would like to know your opinion about this addition.

The goal is to implement a protection for the slowloris attack. It is a work-in-progress but need your approval and point of view to continue working on this.

I read [this discussion](https://github.com/valyala/fasthttp/issues/586) about the scope of fasthttp but I also think this modification is aligned with the timeouts the dev can set.

Also setting timeouts are not enough when a server can receive small and large bodies.

Kind regards,
Mauro.

### CODE REVIEW

**Comment by kirillDanshin** [comment]
I believe that is very much outside the scope of fasthttp. I believe it should be done at lower level (e.g. tcp/udp conn wrapper). having this built into fasthttp will impact some of the major use cases, for example, rtb can't have that much allocations just  suddenly appear out of nowhere, and having this type of defense in place wouldn't work for mid/high profile HLS applications.

we can probably make an addon library for this, publish it in github.com/fasthttp, and put a link in the readme.

**Comment by mxmauro** [comment]
> I believe that is very much outside the scope of fasthttp. I believe it should be done at lower level (e.g. tcp/udp conn wrapper). having this built into fasthttp will impact some of the major use cases, for example, rtb can't have that much allocations just suddenly appear out of nowhere, and having this type of defense in place wouldn't work for mid/high profile HLS applications.
> 
> we can probably make an addon library for this, publish it in github.com/fasthttp, and put a link in the readme.

Hi @kirillDanshin no idea on how to create an add-on (because it affects the connection at a low level) but my intention, for the final version, is to not wrap `net.Conn` if configured values are zero.

**Comment by erikdubbelboer** [comment]
In my opinion this shouldn't really be an issue with the use cases fasthttp is for. **fasthttp is not mean to be used for public webservers**. It's intended use is for some high QPS environments such as OpenRTB or other RTB use cases. There you always have connections between known servers, none of which would try a slowloris attack as you are customers of each other. If you have to expose fasthttp to the open web I would always put something like nginx in front of it. If only for TLS termination. Doing TLS in Go completely goes against the performance gains you would get from fasthttp. fasthttp isn't really meant to be used with https as crypto is still slower in Go than in C.

**Comment by mxmauro** [comment]
Hi @erikdubbelboer I understand.

Thanks to both for explaining the details and the goal of the library.

Kind regards.

**Pull request closed without merging**
