### PR TITLE
support configure HostClient

### PR DESCRIPTION
**Pull request by farss**
ConfigureClient configures the fasthttp.HostClient. 
So I can use https://github.com/dgrr/http2 in fasthttp.Client

### CODE REVIEW

**Comment by erikdubbelboer** [comment]
I'm curious, what do you need to configure that you can't configure on the `fasthttp.Client` itself?

**Comment by erikdubbelboer** [comment]
In that case I would prefer it if you added `Client.Transport` that gets copied to the `HostClient` then, just like all the other options.

**Comment by farss** [comment]
Client 

> In that case I would prefer it if you added `Client.Transport` that gets copied to the `HostClient` then, just like all the other options.

Client don't know Addr of HostClient, So need callback function to config HostClient

**Comment by erikdubbelboer** [comment]
I'm not sure I understand. `HostClient.Transport` is a `func(*Request, *Response) error`. Why can't that be configured on `Client` and passed to `HostClient`? In the Transport function you get the `Request` so you can make decisions based on that?

**Comment by farss** [comment]
HostClient.Transport works on all requests. Sometimes want to config HostClient only after created

**Comment by erikdubbelboer** [comment]
Ok you convinced me 😄

**Comment by farss** [comment]
thank you!

**Comment by zxpdmw** [comment]
如何将fasthttp.Client配置成支持http2协议的, 用新增的ConfigureClient可以吗, 可以提供个demo

**Pull request merged**
