### PR TITLE
Adding errors Request/Response reads

### PR DESCRIPTION
**Pull request by fmstephe**
Currently in order to read from a request or response we needed to read
the entire body into a buffer and then read from that buffer. This
approach does not return any errors that were encountered while reading
from the network. Instead errors are written into the Request/Response
body and can be read from there.

This makes it very hard to reliably determine if an error has occurred.
I have added two very basic functions which do return an explicit error.

One implements current behaviour, read body into buffer and return that,
but returns an explicit error. The second exposes the bodyStream field
as an io.Reader allowing client code to stream data with minimal memory
consumption, as well as exposing errors.

### CODE REVIEW

**Comment by kataras** [comment]
Dear @fmstephe 

Could you, please, write some tests for those ?

Thanks,
kataras

**Comment by fmstephe** [comment]
This PR is in a very basic state. It contains no tests and isn't yet fit for merging. I would like to gauge your interest in this change.

If you are interested, I'll write tests and look more carefully at the implementation.

**Comment by fmstephe** [comment]
@kataras, there are two methods in the PR. I would like to find out which interfaces people are most attracted to before I invest in writing tests.

The main property I would like to have are access to explicit errors when reading from the body of a Request/Response.

**Comment by kataras** [comment]
I don't have access to approve or decline this PR, but without tests it will not be merged.

> It contains no tests and isn't yet fit for merging. I would like to gauge your interest in this change.

I'm ok with this change but I think the `StreamBody()` is already exists with other name, can you lookup and if needed remove this function ?

**Comment by fmstephe** [comment]
@kataras I couldn't find a StreamBody() equivalent. If it exists then I am satisfied and don't need any changes. I'll have another careful look. If anyone can point to these functions I would be very grateful.

**Comment by kataras** [comment]
Yes, you have right the `StreamBody` doesn't exists but I use this method(on a web framework which I maintain):

```go
// StreamReader sets response body stream and, optionally body size.
//
// If bodySize is >= 0, then the bodyStream must provide exactly bodySize bytes
// before returning io.EOF.
//
// If bodySize < 0, then bodyStream is read until io.EOF.
//
// bodyStream.Close() is called after finishing reading all body data
// if it implements io.Closer.
//
// See also StreamReader.
func (ctx *Context) StreamReader(bodyStream io.Reader, bodySize int) {
	ctx.RequestCtx.Response.SetBodyStream(bodyStream, bodySize)
}

```

**Comment by fmstephe** [comment]
@kataras thanks for your pointer, I had misunderstood the way the StreamReader method was intended to be used. So in this scenario you would call the `SetBodyStream(...)` method before you start reading and then you would expect reads to be streamed to the bodyStream arg from then on?

I think this satisfies my needs, I can stream the response body and get to see any errors that occur along the way.

Thanks.

**Comment by kataras** [comment]
Exactly :) Happy to helped, thanks for your interest, fasthttp wants nice contributors like you

**Pull request closed without merging**
