### PR TITLE
[WIP] Add ProxyClient

### PR DESCRIPTION
**Pull request by hnakamur**
See https://github.com/valyala/fasthttp/issues/64 for discussion.

- [x] Create ProxyClient with methods SendRequest, ReadResponseHeader, ReadResponseBody.
- [x] Move ProxyClient to the separate package "proxy".
- [x] Add methods Do and CleanupResponse and remove SendRequest, ReadResponseHeader, ReadResponseBody.
- [ ] Clean up the code.

An example of using a ProxyClient just as a http client is at:
https://github.com/hnakamur/fasthttp/blob/97498c0b12834fe31992796e3af34e0cb0004f1d/proxy/proxy_client_test.go#L39-L65

### CODE REVIEW

**Comment by valyala** [comment]
Try implementing `ProxyClient` in a separate package, so you could spot missing functionality in `fasthttp` for such an implementation.

I'll look into the PR on the next week.

**Comment by hnakamur** [comment]
I copied the source from the net/http package and modified to just enough to work it with ProxyClient.
Am I on the right track? If you agree, I'll try to clean up the copied code a little bit more.

**Comment by valyala** [comment]
I thought a separate `ProxyClient` package will be created outside `fasthttp` namespace, which will use public API provided by `fasthttp`. If the current API isn't enough, then just propose API changes to `fasthttp` in order to satisfy such a `ProxyClient` implementation in a separate package.

**Comment by hnakamur** [comment]
OK. I'm closing this PR.

**Pull request closed without merging**
