### PR TITLE
fix: reset response after reset user values on keep-alive connections

### PR DESCRIPTION
**Pull request by savsgio**
Same as the issue https://github.com/valyala/fasthttp/pull/1162 but with the response!

### CODE REVIEW

**Comment by erikdubbelboer** [comment]
Thanks!

**Comment by ShivanshVij** [comment]
@erikdubbelboer Can we make a new release from the master branch with this change?

**Comment by erikdubbelboer** [comment]
I was not planning on tagging a new release of fasthttp until next year, just to be sure we don't break anything for anyone around this busy time where not everyone works.

**Comment by ShivanshVij** [comment]
That makes a lot of sense, thank you for thinking about that!

**Pull request merged**
