### PR TITLE
Resolve the security issue of GoSec

### PR DESCRIPTION
**Pull request by panjf2000**

### CODE REVIEW

**Comment by dgrr** [comment]
What's the issue about? Can you explain a little?

**Comment by panjf2000** [comment]
To resolve the security issue: https://github.com/valyala/fasthttp/pull/755/checks?check_run_id=497717442

```
[/home/runner/work/fasthttp/fasthttp/server.go:910] - G307 (CWE-): Deferring unsafe method "*os.File" on type "Close" (Confidence: HIGH, Severity: MEDIUM)
  > defer ff.Close()
```
@dgrr

**Comment by panjf2000** [comment]
https://github.com/valyala/fasthttp/pull/755#discussion_r390243756

**Comment by erikdubbelboer** [comment]
Thanks!

**Pull request merged**
