### PR TITLE
NetHTTPResponseWriter support hijackerConn for fasthttp adaptor

### PR DESCRIPTION
**Pull request by yoyofx**
if the request connection upgrade the hijacker connection, that handler needed direct return after  ServeHTTP handler process .

### CODE REVIEW

**Comment by yoyofx** [comment]
> What is `hijackerConn`? Where is `IsHijackerConn` set to true? Why put `Ctx` in there if you're not going to use it?
 
1. because  the netHTTPResponseWriter is not implement Hijacker interface , that is call name  'hijackerConn' .
2. I  need call ctx.Hijack(func(netConn net.Conn) func in  http.Handler , upgrade it to websocket.
3. IsHijackerConn call adpter handler, that's 'Hijack' not needed anything. and then hold the net.conn in  http.Handler.

I used to this example： https://github.com/yoyofx/yoyogo/blob/dev/web/websocketupgrader.go#L49

**Comment by yoyofx** [comment]
readme:
http.Hijacker interface, the Hijack() (net.Conn, *bufio.ReadWriter, error)  is sync func.

ctx.Hijack(func(netConn net.Conn) is callback func ,that is async.
In the 'adpter' .if don't direct return on after call ctx.Hijjack func ,  fasthttp is async process fasthttp.RequestHandler.
and then the net.Conn will not wait to be used.

**Comment by erikdubbelboer** [comment]
I don't understand, with your pull `NetHTTPResponseWriter` still doesn't implement `http.Hijacker`. If that if your desire then why not implement it? Is there code missing in your pull maybe? Right now your just adding fields to the struct and not using them? Can you maybe add a test case that fails before your pull and succeeds after?

**Comment by oSethoum** [comment]
@erikdubbelboer Hi, am having the same issue when using the fasthttpadaptor 
image
how can I fix it?

**Comment by erikdubbelboer** [comment]
I tried implementing this, but it's impossible with the way hijacking works in net/http and fasthttp. They are just incompatible.

**Comment by oSethoum** [comment]
@erikdubbelboer Thanks for trying.

**Pull request closed without merging**
