### PR TITLE
Restart PipelineClient worker on error

### PR DESCRIPTION
**Pull request by erikdubbelboer**
Fixes https://github.com/valyala/fasthttp/issues/832

### CODE REVIEW

**Comment by lithdew** [comment]
I will check more thoroughly later today, apologies for the delay - on a quick skim though, should chW be reset when there are pending messages available?

**Comment by erikdubbelboer** [comment]
`chW` is only reset when there are no message pending.

**Comment by lithdew** [comment]
> `chW` is only reset when there are no message pending.

Tested it on my end and it works; LGTM?

**Comment by erikdubbelboer** [comment]
Thanks

**Pull request merged**
