### PR TITLE
Add option for middleware to set custom remote address

### LINKED ISSUE #1008: Add option to set value of RemoteAddr/RemoteIP by middleware
Maybe pointer to  `net.Addr` could be added to `RequestCtx` set that it could be set by middleware that if set would be used by `RequestCtx.RemoteAddr()` instead of one from `c`.

This would allow implementing more robust and generic middlewares for handling `X-Real-IP` and/or `X-Forwarded-For` etc

### PR DESCRIPTION
**Pull request by lafriks**
Fixes #1008

### CODE REVIEW

**Comment by lafriks** [comment]
lint failure does not seem to be related to my PR :)

**Review by erikdubbelboer — CHANGES_REQUESTED** [review]
It's probably best to also set `ctx.remoteAddr = nil` in `RequestCtx.Init2`.

**Comment by lafriks** [comment]
> It's probably best to also set `ctx.remoteAddr = nil` in `RequestCtx.Init2`.

ok, will add. Should I remove that from `releaseCtx`?

**Comment by lafriks** [comment]
@erikdubbelboer fixed

**Comment by erikdubbelboer** [comment]
Thanks!

**Comment by lafriks** [comment]
Thanks for prompt review

**Comment by lafriks** [comment]
would be nice to tag version so that it would be easier to use it :)

**Comment by erikdubbelboer** [comment]
Done

**Pull request merged**
